import type { CareerEventDef } from '../engine/types'

/** Eventos contextuales por país del club / confederación. */
export const REGIONAL_EVENTS: CareerEventDef[] = [
  {
    id: 'mx_food_poisoning',
    impact: 'ruin',
    titleKey: 'events.mx_food_poisoning.title',
    bodyKey: 'events.mx_food_poisoning.body',
    weight: 14,
    minAge: 17,
    requiresClub: true,
    clubCountries: ['MEX'],
    regional: true,
    choices: [
      { id: 'rest', labelKey: 'events.mx_food_poisoning.rest' },
      { id: 'play_through', labelKey: 'events.mx_food_poisoning.play' },
    ],
  },
  {
    id: 'mx_clasico_pressure',
    impact: 'normal',
    titleKey: 'events.mx_clasico_pressure.title',
    bodyKey: 'events.mx_clasico_pressure.body',
    weight: 12,
    minAge: 18,
    requiresClub: true,
    clubCountries: ['MEX'],
    minClubRep: 2,
    regional: true,
    choices: [
      { id: 'embrace', labelKey: 'events.mx_clasico_pressure.embrace' },
      { id: 'hide', labelKey: 'events.mx_clasico_pressure.hide' },
    ],
  },
  {
    id: 'ar_media_pressure',
    impact: 'normal',
    titleKey: 'events.ar_media_pressure.title',
    bodyKey: 'events.ar_media_pressure.body',
    weight: 13,
    minAge: 18,
    requiresClub: true,
    clubCountries: ['ARG'],
    regional: true,
    choices: [
      { id: 'face_cameras', labelKey: 'events.ar_media_pressure.face' },
      { id: 'silence', labelKey: 'events.ar_media_pressure.silence' },
    ],
  },
  {
    id: 'ar_clasico_week',
    impact: 'boost',
    titleKey: 'events.ar_clasico_week.title',
    bodyKey: 'events.ar_clasico_week.body',
    weight: 11,
    minAge: 17,
    requiresClub: true,
    clubCountries: ['ARG'],
    minClubRep: 2,
    regional: true,
    choices: [
      { id: 'ready', labelKey: 'events.ar_clasico_week.ready' },
      { id: 'nervous', labelKey: 'events.ar_clasico_week.nervous' },
    ],
  },
  {
    id: 'ar_ascenso_opportunity',
    impact: 'fortune',
    titleKey: 'events.ar_ascenso_opportunity.title',
    bodyKey: 'events.ar_ascenso_opportunity.body',
    weight: 10,
    maxAge: 23,
    requiresClub: true,
    clubCountries: ['ARG'],
    maxClubRep: 2,
    regional: true,
    choices: [
      { id: 'seize', labelKey: 'events.ar_ascenso_opportunity.seize' },
      { id: 'pass', labelKey: 'events.ar_ascenso_opportunity.pass' },
    ],
  },
  {
    id: 'br_calendar_fatigue',
    impact: 'ruin',
    titleKey: 'events.br_calendar_fatigue.title',
    bodyKey: 'events.br_calendar_fatigue.body',
    weight: 12,
    minAge: 19,
    requiresClub: true,
    clubCountries: ['BRA'],
    regional: true,
    choices: [
      { id: 'rotate', labelKey: 'events.br_calendar_fatigue.rotate' },
      { id: 'push', labelKey: 'events.br_calendar_fatigue.push' },
    ],
  },
  {
    id: 'br_rival_serie_a',
    impact: 'normal',
    titleKey: 'events.br_rival_serie_a.title',
    bodyKey: 'events.br_rival_serie_a.body',
    weight: 11,
    minAge: 18,
    requiresClub: true,
    clubCountries: ['BRA'],
    minClubRep: 2,
    regional: true,
    choices: [
      { id: 'listen', labelKey: 'events.br_rival_serie_a.listen' },
      { id: 'reject', labelKey: 'events.br_rival_serie_a.reject' },
    ],
  },
  {
    id: 'br_carnival_break',
    impact: 'fortune',
    titleKey: 'events.br_carnival_break.title',
    bodyKey: 'events.br_carnival_break.body',
    weight: 9,
    requiresClub: true,
    clubCountries: ['BRA'],
    regional: true,
    choices: [
      { id: 'rest', labelKey: 'events.br_carnival_break.rest' },
      { id: 'party', labelKey: 'events.br_carnival_break.party' },
    ],
  },
  {
    id: 'eu_travel_fatigue',
    impact: 'normal',
    titleKey: 'events.eu_travel_fatigue.title',
    bodyKey: 'events.eu_travel_fatigue.body',
    weight: 10,
    minAge: 20,
    requiresClub: true,
    confederations: ['UEFA'],
    minClubRep: 3,
    regional: true,
    choices: [
      { id: 'recover', labelKey: 'events.eu_travel_fatigue.recover' },
      { id: 'play', labelKey: 'events.eu_travel_fatigue.play' },
    ],
  },
  {
    id: 'eu_adaptation',
    impact: 'normal',
    titleKey: 'events.eu_adaptation.title',
    bodyKey: 'events.eu_adaptation.body',
    weight: 12,
    maxAge: 24,
    requiresClub: true,
    confederations: ['UEFA'],
    regional: true,
    choices: [
      { id: 'integrate', labelKey: 'events.eu_adaptation.integrate' },
      { id: 'isolate', labelKey: 'events.eu_adaptation.isolate' },
    ],
  },
  {
    id: 'mena_exit_clause',
    impact: 'boost',
    titleKey: 'events.mena_exit_clause.title',
    bodyKey: 'events.mena_exit_clause.body',
    weight: 11,
    minAge: 22,
    requiresClub: true,
    clubCountries: ['KSA', 'QAT', 'UAE'],
    regional: true,
    choices: [
      { id: 'accept_money', labelKey: 'events.mena_exit_clause.accept' },
      { id: 'keep_clause', labelKey: 'events.mena_exit_clause.keep' },
    ],
  },
  {
    id: 'mls_adaptation',
    impact: 'normal',
    titleKey: 'events.mls_adaptation.title',
    bodyKey: 'events.mls_adaptation.body',
    weight: 11,
    requiresClub: true,
    clubCountries: ['USA', 'CAN'],
    regional: true,
    choices: [
      { id: 'buy_in', labelKey: 'events.mls_adaptation.buy' },
      { id: 'tourist', labelKey: 'events.mls_adaptation.tourist' },
    ],
  },
  {
    id: 'concacaf_heat',
    impact: 'ruin',
    titleKey: 'events.concacaf_heat.title',
    bodyKey: 'events.concacaf_heat.body',
    weight: 9,
    requiresClub: true,
    confederations: ['CONCACAF'],
    regional: true,
    choices: [
      { id: 'hydrate', labelKey: 'events.concacaf_heat.hydrate' },
      { id: 'ignore', labelKey: 'events.concacaf_heat.ignore' },
    ],
  },
]

export function getRegionalEventDef(id: string): CareerEventDef | undefined {
  return REGIONAL_EVENTS.find((e) => e.id === id)
}
