// src/features/career/nationalities-fifa.ts — Copero (MGC-655)
//
// Lista completa de países afiliados a FIFA (~210) con código ISO alpha-2,
// nombre en español y emoji de bandera. Reemplaza al subset curado de
// `nationalities.ts` (34 entries) cuando el operador quiere paridad literal
// con copero.top (HomepageCareerStarter kiya0908), que expone los 15 priority
// + alfabético de los ~220 países FIFA.
//
// Uso: el form del home consume `NATIONALITIES_FIFA` con `PRIORITY_FIFA_CODES`
// arriba y el resto alfabético abajo (ADR-0015 §2). El archivo pesa ~3.5 KB
// raw, aceptable para el chunk inicial del home (verificado post-build).

import type { Nationality } from '@/types/career';

export const NATIONALITIES_FIFA: Nationality[] = [
  // Priority FIFA — los 15 que kiya0908 pone arriba (copero.top)
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'BR', name: 'Brasil', flag: '🇧🇷' },
  { code: 'MX', name: 'México', flag: '🇲🇽' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'ES', name: 'España', flag: '🇪🇸' },
  { code: 'GB', name: 'Inglaterra', flag: '🇬🇧' },
  { code: 'IT', name: 'Italia', flag: '🇮🇹' },
  { code: 'FR', name: 'Francia', flag: '🇫🇷' },
  { code: 'DE', name: 'Alemania', flag: '🇩🇪' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'US', name: 'Estados Unidos', flag: '🇺🇸' },
  { code: 'NL', name: 'Países Bajos', flag: '🇳🇱' },
  { code: 'BE', name: 'Bélgica', flag: '🇧🇪' },

  // Resto alfabético (FIFA member associations)
  { code: 'AF', name: 'Afganistán', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AG', name: 'Antigua y Barbuda', flag: '🇦🇬' },
  { code: 'SA', name: 'Arabia Saudita', flag: '🇸🇦' },
  { code: 'DZ', name: 'Argelia', flag: '🇩🇿' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaiyán', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BD', name: 'Bangladés', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BH', name: 'Baréin', flag: '🇧🇭' },
  { code: 'BZ', name: 'Belice', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benín', flag: '🇧🇯' },
  { code: 'BY', name: 'Bielorrusia', flag: '🇧🇾' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnia y Herzegovina', flag: '🇧🇦' },
  { code: 'BW', name: 'Botsuana', flag: '🇧🇼' },
  { code: 'BN', name: 'Brunéi', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'BT', name: 'Bután', flag: '🇧🇹' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'KH', name: 'Camboya', flag: '🇰🇭' },
  { code: 'CM', name: 'Camerún', flag: '🇨🇲' },
  { code: 'CA', name: 'Canadá', flag: '🇨🇦' },
  { code: 'QA', name: 'Catar', flag: '🇶🇦' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩' },
  { code: 'CZ', name: 'Chequia', flag: '🇨🇿' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'CY', name: 'Chipre', flag: '🇨🇾' },
  { code: 'VA', name: 'Ciudad del Vaticano', flag: '🇻🇦' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: 'KP', name: 'Corea del Norte', flag: '🇰🇵' },
  { code: 'KR', name: 'Corea del Sur', flag: '🇰🇷' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CI', name: 'Costa de Marfil', flag: '🇨🇮' },
  { code: 'HR', name: 'Croacia', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'DK', name: 'Dinamarca', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', name: 'Egipto', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'AE', name: 'Emiratos Árabes Unidos', flag: '🇦🇪' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷' },
  { code: 'SK', name: 'Eslovaquia', flag: '🇸🇰' },
  { code: 'SI', name: 'Eslovenia', flag: '🇸🇮' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'ET', name: 'Etiopía', flag: '🇪🇹' },
  { code: 'PH', name: 'Filipinas', flag: '🇵🇭' },
  { code: 'FI', name: 'Finlandia', flag: '🇫🇮' },
  { code: 'FJ', name: 'Fiyi', flag: '🇫🇯' },
  { code: 'GA', name: 'Gabón', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GD', name: 'Granada', flag: '🇬🇩' },
  { code: 'GR', name: 'Grecia', flag: '🇬🇷' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳' },
  { code: 'GQ', name: 'Guinea Ecuatorial', flag: '🇬🇶' },
  { code: 'GW', name: 'Guinea-Bisáu', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'Haití', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', name: 'Hungría', flag: '🇭🇺' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶' },
  { code: 'IE', name: 'Irlanda', flag: '🇮🇪' },
  { code: 'IR', name: 'Irán', flag: '🇮🇷' },
  { code: 'IS', name: 'Islandia', flag: '🇮🇸' },
  { code: 'MH', name: 'Islas Marshall', flag: '🇲🇭' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JP', name: 'Japón', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordania', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazajistán', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenia', flag: '🇰🇪' },
  { code: 'KG', name: 'Kirguistán', flag: '🇰🇬' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LS', name: 'Lesoto', flag: '🇱🇸' },
  { code: 'LV', name: 'Letonia', flag: '🇱🇻' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'Libia', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'Lituania', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxemburgo', flag: '🇱🇺' },
  { code: 'LB', name: 'Líbano', flag: '🇱🇧' },
  { code: 'MK', name: 'Macedonia del Norte', flag: '🇲🇰' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MY', name: 'Malasia', flag: '🇲🇾' },
  { code: 'MW', name: 'Malaui', flag: '🇲🇼' },
  { code: 'MV', name: 'Maldivas', flag: '🇲🇻' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'ML', name: 'Malí', flag: '🇲🇱' },
  { code: 'MA', name: 'Marruecos', flag: '🇲🇦' },
  { code: 'MU', name: 'Mauricio', flag: '🇲🇺' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷' },
  { code: 'MD', name: 'Moldavia', flag: '🇲🇩' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'MC', name: 'Mónaco', flag: '🇲🇨' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'NO', name: 'Noruega', flag: '🇳🇴' },
  { code: 'NZ', name: 'Nueva Zelanda', flag: '🇳🇿' },
  { code: 'NE', name: 'Níger', flag: '🇳🇪' },
  { code: 'OM', name: 'Omán', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistán', flag: '🇵🇰' },
  { code: 'PW', name: 'Palaos', flag: '🇵🇼' },
  { code: 'PA', name: 'Panamá', flag: '🇵🇦' },
  { code: 'PG', name: 'Papúa Nueva Guinea', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'Perú', flag: '🇵🇪' },
  { code: 'PL', name: 'Polonia', flag: '🇵🇱' },
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: 'CF', name: 'República Centroafricana', flag: '🇨🇫' },
  { code: 'CD', name: 'República Democrática del Congo', flag: '🇨🇩' },
  { code: 'DO', name: 'República Dominicana', flag: '🇩🇴' },
  { code: 'RW', name: 'Ruanda', flag: '🇷🇼' },
  { code: 'RO', name: 'Rumanía', flag: '🇷🇴' },
  { code: 'RU', name: 'Rusia', flag: '🇷🇺' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'KN', name: 'San Cristóbal y Nieves', flag: '🇰🇳' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: 'VC', name: 'San Vicente y las Granadinas', flag: '🇻🇨' },
  { code: 'LC', name: 'Santa Lucía', flag: '🇱🇨' },
  { code: 'ST', name: 'Santo Tomé y Príncipe', flag: '🇸🇹' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leona', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapur', flag: '🇸🇬' },
  { code: 'SY', name: 'Siria', flag: '🇸🇾' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'ZA', name: 'Sudáfrica', flag: '🇿🇦' },
  { code: 'SD', name: 'Sudán', flag: '🇸🇩' },
  { code: 'SS', name: 'Sudán del Sur', flag: '🇸🇸' },
  { code: 'SE', name: 'Suecia', flag: '🇸🇪' },
  { code: 'CH', name: 'Suiza', flag: '🇨🇭' },
  { code: 'SR', name: 'Surinam', flag: '🇸🇷' },
  { code: 'EH', name: 'Sáhara Occidental', flag: '🇪🇭' },
  { code: 'TH', name: 'Tailandia', flag: '🇹🇭' },
  { code: 'TW', name: 'Taiwán', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'TJ', name: 'Tayikistán', flag: '🇹🇯' },
  { code: 'TL', name: 'Timor Oriental', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad y Tobago', flag: '🇹🇹' },
  { code: 'TM', name: 'Turkmenistán', flag: '🇹🇲' },
  { code: 'TR', name: 'Turquía', flag: '🇹🇷' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'TN', name: 'Túnez', flag: '🇹🇳' },
  { code: 'UA', name: 'Ucrania', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UZ', name: 'Uzbekistán', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
  { code: 'DJ', name: 'Yibuti', flag: '🇩🇯' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabue', flag: '🇿🇼' },
];

/** Priority FIFA (kiya0908 copero.top). Lista de códigos ISO-2 que se muestran
 *  arriba del select antes del alfabético. */
export const PRIORITY_FIFA_CODES: readonly string[] = [
  'AR', 'BR', 'MX', 'UY', 'CO', 'CL', 'ES', 'GB', 'IT', 'FR', 'DE', 'PT', 'US', 'NL', 'BE',
];

/** Catálogo de modos de draft (MGC-655 — kiya0908 HomepageCareerStarter). */
export const DRAFT_MODES = ['classic', 'purist'] as const;
export type DraftMode = (typeof DRAFT_MODES)[number];

export const DRAFT_MODE_LABEL: Record<DraftMode, string> = {
  classic: 'Clásico',
  purist: 'Purista',
};

export const DRAFT_MODE_DESCRIPTION: Record<DraftMode, string> = {
  classic: 'Elegí entre cartas legendarias con sus puntos fuertes',
  purist: 'Reparto equitativo entre atributos, sin ventajas',
};
